[package]
authors = ["Eric Kidd <git@randomhacks.net>"]
description = "Fetch secrets from either environment variables or Hashicorp's Vault"
documentation = "http://docs.rs/credentials/"
license = "CC0-1.0"
name = "credentials"
readme = "README.md"
repository = "https://github.com/emk/credentials"
version = "0.10.0"

[dependencies]
failure = "0.1.1"
hyper = { version = "0.11", default-features = false }
lazy_static = "1.1"
log = "0.4"
regex = "1.0"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dirs = "1.0.5"

[dev-dependencies]
env_logger = "0.5"
